name: {{name}}
description: "This is default {{name}} description."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  api:
    path: ../../shared/api
  components:
    path: ../../shared/components
  core:
    path: ../../shared/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis:
    path: ../../shared/analysis
